#!/usr/bin/env bash

## Install ansible
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install ansible

## Pull ansible
sudo ansible-pull -U https://github.com/bottlerocketjonny/ansible.git
