- name: Add KeePassXC PPA (Ubuntu)
  apt_repository:
    repo: ppa:phoerious/keepassxc
    state: present
  when: ansible_distribution == 'Ubuntu'
  tags:
    - install
    - keepassxc

- name: Install KeePassXC
  apt:
    name: keepassxc
    state: present
    update_cache: yes
  tags:
    - install
    - keepassxc
