tasks:
- name: Download NVM install script
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
    dest: "/tmp/install_nvm.sh"
    mode: '0755'
  tags:
    - install
    - node
    - nvm

- name: Install NVM
  shell: bash /tmp/install_nvm.sh
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  tags:
    - install
    - node
    - nvm

- name: Install Node.js LTS version using NVM
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh &&
    nvm install --lts &&
    nvm use --lts &&
    nvm alias default 'lts/*'
  args:
    executable: /bin/bash
  tags:
    - install
    - node
    - nvm

- name: Set NPM global prefix and add to PATH
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      export NPM_CONFIG_PREFIX=~/.npm-global
      export PATH=~/.npm-global/bin:$PATH
  tags:
    - install
    - node
    - npm-path
