- name: Download Postman tarball
  get_url:
    url: https://dl.pstmn.io/download/latest/linux64
    dest: /tmp/postman.tar.gz
  tags:
    - install
    - postman

- name: Create Postman directory
  file:
    path: /opt/postman
    state: directory
  tags:
    - install
    - postman

- name: Extract Postman tarball
  ansible.builtin.unarchive:
    src: /tmp/postman.tar.gz
    dest: /opt/postman
    remote_src: yes
    extra_opts: [--strip-components=1]
  tags:
    - install
    - postman

- name: Create symlink to Postman binary
  file:
    src: /opt/postman/Postman
    dest: /usr/local/bin/postman
    state: link
  tags:
    - install
    - postman
