- name: Ensure .ssh directory exists.
  become: true
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  become: true
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key public
  become: true
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Add SSH key to authorized_keys
  ansible.builtin.authorized_key:
    user: jonny
    state: present
    key: "{{ lookup('file', '/home/jonny/.ssh/id_rsa_github.pub') }}"

